AWSTemplateFormatVersion: 2010-09-09
Description: | 
  This cloudformation file is created to deploy roman numeral converter application.

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP for Apache Web Server and SSH for secure connection"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0715c1897453cabd1
      InstanceType: t2.micro
      KeyName: first-key-pair
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData:
       Fn::Base64:
        !Sub |
         #! /bin/bash
            yum update -y
            yum install git -y
            yum install python-pip -y
            HOME=/root
            git clone https://github.com/mkasimkuzi/my-projects.git
            cd /my-projects/roman-latin-project
            pip3 install flask
            python3 app.py
Outputs:
  WebSiteURL:
   Value: !Sub
   - http://${PublicAddress}
   - PublicAddress: !GetAtt WebServerHost.PublicDnsName